# 伺服器設定
server:
  port: 8080  # 設定伺服器運行的端口為 8080

spring:
  # 設定應用程式名稱
  application:
    name: AppleJuice

  # 安全性設定
  security:

  # 資料庫連線設定
  datasource:
    url: jdbc:mysql://mysql.zeabur.internal:3306/zeabur?useSSL=false&serverTimezone=Asia/Taipei  # 資料庫連線 URL，包含資料庫名稱、時區等設定
    username: root  # 資料庫使用者名稱
    password: P625qutSn4QkXpNwB9F38Dcgm0zyr71h  # 資料庫密碼
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 驅動程式的類別名稱

  # JPA 設定
  jpa:
    hibernate:
      ddl-auto: update  # 設定 Hibernate 自動管理資料庫結構，選擇 "update" 表示自動更新資料庫結構
    show-sql: true  # 是否在控制台顯示執行的 SQL 查詢語句，開啟方便除錯

springdoc:
  swagger-ui:
    urls:
      - name: "AppleJucie專案"
        url: "https://applejuice.zeabur.app/v3/api-docs"
      - name: "CMATH專案"
        url: "http://10.2.15.82:8081/api/v2/api-docs"
      - name: "CMCST專案"
        url: "http://10.2.15.82:8082/api/CM/CST/v2/api-docs"
      - name: "CMPRD專案"
        url: "http://10.2.15.82:8083/api/CM/PRD/v2/api-docs"