# 伺服器設定
server:
  port: 8080  # 設定伺服器運行的端口為 8080

spring:
  # 設定應用程式名稱
  application:
    name: AppleJuice
  cloud:
    vault:
      enabled: false
      uri: http://localhost:8200
      token: xxx
      kv:
        enabled: true
        backend: secret
        default-context: AppleJuice
#  config: # 對應 vault 開啟關閉而註解
#    import: vault://

  # 安全性設定
  security:

  # JWT 設定
  jwt:
    secret: mySecretKey123
#    secret: ${vault.jwt.secret}  # 從 Vault 獲取 JWT 密鑰
    expiration: 300  # 秒

  # 資料庫連線設定
  datasource:
    mysql:
      url: jdbc:mysql://hkg1.clusters.zeabur.com:32652/AppleJuice?useSSL=false&serverTimezone=Asia/Taipei
      username: root
      password: P625qutSn4QkXpNwB9F38Dcgm0zyr71h
#      url: jdbc:mysql://localhost:3306/AppleJuice?useSSL=false&serverTimezone=Asia/Taipei
#      username: root
#      password: root
#      url: ${vault.mysql.url}  # 從 Vault 獲取 MySQL 連線 URL
#      username: ${vault.mysql.username}  # 從 Vault 獲取 MySQL 用戶名
#      password: ${vault.mysql.password}  # 從 Vault 獲取 MySQL 密碼
      driver-class-name: com.mysql.cj.jdbc.Driver

#    mssql:
#      url: jdbc:sqlserver://localhost:1433;databaseName=AppleJuice;encrypt=false
#      username: sa
#      password: 1qaz@WSX
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # JPA 設定
  jpa:
    show-sql: true  # 是否在控制台顯示執行的 SQL 查詢語句，開啟方便除錯

  # Liquibase 設定
  liquibase:
    enabled: true
    # 設定 Liquibase 的變更日誌文件
    change-log: classpath:db/changelog/changelog-master.xml
    # 管理 MySQL 資料庫
    url: ${spring.datasource.mysql.url}
    user: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    driver-class-name: ${spring.datasource.mysql.driver-class-name}

# 監控端點設定
management:
  endpoint:
    health:
      show-details: always  # 顯示所有健康檢查器的詳細資訊
  endpoints:
    web:
      base-path: /monitor # 監控端點的基本路徑
      exposure:
        include: refresh,health  # 啟用 refresh 端點