# 伺服器設定
server:
  port: 8080  # 設定伺服器運行的端口為 8080

spring:
  # 設定應用程式名稱
  application:
    name: AppleJuice

  # 安全性設定
  security:

  # JWT 設定
  jwt:
    secret: mySecretKey123
    expiration: 300  # 秒

  # 資料庫連線設定
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/AppleJuice?useSSL=false&serverTimezone=Asia/Taipei
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

#    mssql:
#      url: jdbc:sqlserver://localhost:1433;databaseName=AppleJuice;encrypt=false
#      username: sa
#      password: 1qaz@WSX
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # JPA 設定
  jpa:
    show-sql: true  # 是否在控制台顯示執行的 SQL 查詢語句，開啟方便除錯

  # Liquibase 設定
  liquibase:
    enabled: true
    # 設定 Liquibase 的變更日誌文件
    change-log: classpath:db/changelog/changelog-master.xml
    # 管理 MySQL 資料庫
    url: ${spring.datasource.mysql.url}
    user: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    driver-class-name: ${spring.datasource.mysql.driver-class-name}

## 設定日誌級別
#logging:
#  level:
#    root: INFO
#    org.springframework: INFO
#    com.applejuice: INFO
#  file:
#    path: logs
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) [%X{traceId}] - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"