# 伺服器設定
server:
  port: 8080  # 設定伺服器運行的端口為 8080

spring:
  # 設定應用程式名稱
  application:
    name: AppleJuice

  # 安全性設定
  security:

  # 資料庫連線設定
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/AppleJuice?useSSL=false&serverTimezone=Asia/Taipei
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    mssql:
      url: jdbc:sqlserver://localhost:1433;databaseName=AppleJuice;encrypt=false
      username: sa
      password: 1qaz@WSX
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # JPA 設定
  jpa:
    show-sql: true  # 是否在控制台顯示執行的 SQL 查詢語句，開啟方便除錯

  # Flyway 設定
  flyway:
    enabled: true
    url: ${spring.datasource.mysql.url}
    user: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    locations: classpath:db/migration